### ISSUE TITLE
No highlight for markdown files

### ISSUE THREAD

**Issue by rk-terence** [skarline/zed-xcode-themes#1]
Thank you for your amazing work! I have been using this theme once I have tried it. 
I have found one aspect that can be improved, though: currently there is no highlight for markdown files. The default themes in Zed provide syntax highlight for markdown files, but when using this theme, the syntax highlights in markdown files are gone.

It will be much appreciated if syntax highlight support for markdown can be added!

Screenshot using Solarized Light: 
<img width="268" alt="image" src="https://github.com/skarline/zed-xcode-themes/assets/28799257/fe29c6d8-f1da-4184-a7ed-ad47feca3fc8">

Screenshot of the same markdown file using theme XCode Default Light:
<img width="246" alt="image" src="https://github.com/skarline/zed-xcode-themes/assets/28799257/a1f866d0-b880-4e92-86ea-d0e8f092680f">

**Comment by failable** [comment]
Same issue

**Comment by skarline** [comment]
Thank you for the feedback! I have updated the themes to include proper highlighting support for Markdown. Make sure to update the extension to the latest version to check it out.

Feel free to open a new issue if you discover any other areas for improvement :)
